### ISSUE TITLE
No picture for the elephant

### ISSUE THREAD

**Issue by weierstrass** [begogna/begogna.github.io#4]
When you click on the elephant, there is no picture.

**Comment by begogna** [comment]
yes i know, it is on going

On Thu, Apr 9, 2015 at 11:00 PM, weierstrass notifications@github.com
wrote:

> When you click on the elephant, there is no picture.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/begogna/begogna.github.io/issues/4.

## 

Bego
