### ISSUE TITLE
Remove text from template in detailed view of project

### ISSUE THREAD

**Issue by weierstrass** [begogna/begogna.github.io#5]
When you click on an image to see it more detailed you have this text in the bottom:

```
Client: Start Bootstrap    Date: January 2015  Service: Web Development
```

It can be removed.

**Comment by begogna** [comment]
I know, I was going to erase it but I wanted to thing what to put instead
before

On Thu, Apr 9, 2015 at 11:01 PM, weierstrass notifications@github.com
wrote:

> When you click on an image to see it more detailed you have this text in
> the bottom:
> 
> Client: Start Bootstrap    Date: January 2015  Service: Web Development
> 
> It can be removed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/begogna/begogna.github.io/issues/5.

## 

Bego
