### ISSUE TITLE
It could be nice to have the image of the boite a crayons

### ISSUE THREAD

**Issue by weierstrass** [begogna/begogna.github.io#6]
for example under the interactive 3D model.

**Comment by begogna** [comment]
i thought it was repetitive, as it was in the first page image...

On Thu, Apr 9, 2015 at 11:02 PM, weierstrass notifications@github.com
wrote:

> for example under the interactive 3D model.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/begogna/begogna.github.io/issues/6.

## 

Bego
